### ISSUE TITLE
Crash on creating new world

### ISSUE THREAD

**Issue by Lach01298** [juraj-hrivnak/Greenery#10]
[crash-2023-03-11_13.55.40-server.txt](https://github.com/juraj-hrivnak/Greenery/files/10947436/crash-2023-03-11_13.55.40-server.txt)

**Comment by juraj-hrivnak** [comment]
I need to update the Fiuidlogged API.
Until then you can use v1.9.0.6

**Comment by juraj-hrivnak** [comment]
Fixed in `v3.1`

**Comment by Lach01298** [comment]
Still happens in 3.1 with latest Fluidlogged API.
[crash-2023-03-12_14.29.53-server.txt](https://github.com/juraj-hrivnak/Greenery/files/10949916/crash-2023-03-12_14.29.53-server.txt)

**Comment by juraj-hrivnak** [comment]
Interesting. Try to delete the config file for Greenery. It looks like there is error in parsing it.

**Comment by Lach01298** [comment]
Deleted configs, still get the same crash.

**Comment by juraj-hrivnak** [comment]
Can you send the full latest.log?

**Comment by juraj-hrivnak** [comment]
@Lach01298
I still can not reproduce this.
Can you send the full latest log and, if possible, the debug log too, and also the config file?

**Comment by juraj-hrivnak** [comment]
Oh okay, now I know what’s causing it. Biome configured in the config doesn’t exist.

**Comment by FranklinMCA** [comment]
Hey! I have the same problem here.
[crash-2023-03-13_21.41.30-server.txt](https://github.com/juraj-hrivnak/Greenery/files/10961748/crash-2023-03-13_21.41.30-server.txt)

**Comment by juraj-hrivnak** [comment]
For now you can fix the issue by removing the biomesoplenty:pasture biome from the barley’s world gen config.

**Comment by FranklinMCA** [comment]
It works. Thank u for your help!
